Adds a new marker accessibility sample
googlemaps/js-samples pull request #638
Opened 2021-03-23 18:46 UTC by willum070

This PR adds a new sample to demonstrate how to make markers accessible.

Fixes #637 🦕

2021-03-23 18:54 UTC, jpoehnelt requested changes

2021-03-23 18:54 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    infowindow.open(marker.get("map"), marker);
```suggestion
    infowindow.open(marker.getMap(), marker);
```

2021-03-23 18:54 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      position: { lat: pos[0], lng: pos[1],
why not pass the title and label to the constructor?

2021-03-23 18:54 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +  const infowindow = new google.maps.InfoWindow({
might be better to use a single infowindow that we update?

2021-03-23 18:54 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    content: titleText,
```suggestion
    content: marker.getTitle(),
```

2021-03-23 19:55 UTC, jpoehnelt requested changes
This should allow a single infowindow that moves as the user triggers the click event on the marker.

2021-03-23 19:55 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    setupMarker(marker);
```suggestion
    marker.addListener("click", () => {
      infowindow.close();
      infowindow.setContent(marker.getTitle());
      infowindow.open(marker.getMap(), marker);
    });
```

2021-03-23 19:55 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +  const infowindow = new google.maps.InfoWindow();
move this after `const map = google.maps.Map`

2021-03-23 19:55 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +function setupMarker(marker: google.maps.Marker) {
delete this function

2021-03-23 20:56 UTC, jpoehnelt requested changes
simplifying with forEach

could also do `const markers = titleText.map` and return the marker.

2021-03-23 20:56 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      label: (i + 1).toString(),
```suggestion
      label: `${i + 1}`,
```

2021-03-23 20:56 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +  for (let i = 0; i < titleText.length; ++i) {
```suggestion
titleText.forEach((title, i) => {
```

2021-03-23 20:56 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +}
```suggestion
});
```

2021-03-23 20:56 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      title: titleText[i],
```suggestion
      title,
```

2021-03-23 20:56 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      map: map,
```suggestion
      map,
```

2021-03-23 23:40 UTC, jpoehnelt requested changes

2021-03-23 23:40 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    [34.8791806, -111.8265049], // Boynton Pass
convert these to LatLngLiterals, `{lat: 0, lng: 1}`

2021-03-23 23:40 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      position: { lat: pos[0], lng: pos[1],
```suggestion
      position
```

2021-03-23 23:40 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    const pos = tourStops[i];
```suggestion
    const position = tourStops[i];
```

2021-03-23 23:40 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +  const tourStops: [number, number][] = [
```suggestion
  const tourStops: google.maps.LatLngLiteral[] = [
```

2021-03-24 00:44 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +  ];
Can the data structures holding the latLngs and the titles be combined? seems more realistic (and easier) that way?

2021-03-24 00:45 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +  const infowindow = new google.maps.InfoWindow();
s/infowindow/infoWindow/

2021-03-24 00:46 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +      label: `${i + 1}`,
if there is a title then the label is not presented for a11y
if the number is important, best practice might be to make the title `(i + 1) + '. ' + title`

2021-03-24 00:47 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +      infowindow.close();
might be good to comment why the close is needed

2021-03-24 00:48 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +    "Marker five: Bell Rock, the final stop on our tour!",
people don't usually title markers with "marker" in them.

also, there is a lack of parallelism here.

2021-03-24 00:49 UTC, chrisjshull commented on samples/marker-accessibility/src/index.ts
> +      "cycle through the map controls.",
I don't think we want this meta-description in any one marker. I would make all the marker titling consistent.

2021-03-25 15:43 UTC, jpoehnelt requested changes

2021-03-25 15:43 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +    [{lat: 34.8559195, lng: -111.7988186}, "Airport Mesa"],
`npm run format` or `bazel run //:eslint-fix`

2021-03-25 15:43 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      position: item[0],
```suggestion
      position,
```

2021-03-25 15:43 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +      title: `${i + 1}` + ". " + item[1],
```suggestion
      title: `${i + 1}.${title}`,
```

2021-03-25 15:44 UTC, jpoehnelt commented on samples/marker-accessibility/src/index.ts
> +  tourStops.forEach((item, i) => {
```suggestion
  tourStops.forEach(([position, title], i) => {
```

2021-03-31 16:53 UTC, merged